import Foundation

// MARK: - Category

/// Which "life area" calendar an event or goal belongs to.
///
/// This used to be a fixed `enum`, but since you want to create, rename,
/// and recolor categories yourself from Settings, it needs to be a `struct`
/// instead — real data you make, not a fixed list baked into the code.
struct CalendarCategory: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String

    // Stored as a hex string like "#4A7FE8" — simple to save to disk and
    // easy to turn into a SwiftUI `Color` when it's time to draw something.
    var colorHex: String

    /// What a brand-new user starts with. You said Work / Personal / School
    /// as sensible defaults — these get created once, the first time the
    /// app runs, and from then on the user's own edits take over.
    static let defaultCategories: [CalendarCategory] = [
        CalendarCategory(name: "Work", colorHex: "#4A7FE8"),
        CalendarCategory(name: "Personal", colorHex: "#8E5CC7"),
        CalendarCategory(name: "School", colorHex: "#C9922E")
    ]
}

// MARK: - Event

/// A single event living inside one of the category calendars.
///
/// This is a `struct`, not a `class`. In Swift, structs are the default
/// choice for plain data — they're copied by value (similar to how a
/// JS object gets cloned with spread syntax `{...obj}`), which avoids bugs
/// where two different parts of your app accidentally share and mutate
/// the same object without meaning to.
struct CalendarEvent: Identifiable, Codable {
    var id: UUID = UUID()              // a unique ID, generated automatically
    var title: String
    var notes: String = ""
    var startDate: Date
    var endDate: Date

    // Points at a CalendarCategory's `id` rather than storing the category
    // itself. This way, if you rename "Work" to "Job" in Settings, every
    // event tagged with it updates automatically — there's only ever one
    // copy of the category's actual name and color.
    var categoryID: UUID

    // These two flags are the heart of your "calendars feed into each other" idea.
    var flowsToDaily: Bool = false     // should this appear in the Daily time-blocked view?
    var flowsToMaster: Bool = false    // should this appear in the Master overview?

    // `UUID?` means "a UUID, or nothing at all" — this is an Optional.
    // Swift forces you to handle the "nothing" case explicitly, which is
    // stricter than JS/Python but catches a lot of bugs before they happen.
    var linkedGoalID: UUID? = nil      // set only if this event was generated by a Goal
    var isCompleted: Bool = false      // relevant for goal-linked events you can "tick off"
}

// MARK: - Goal

/// How often a goal repeats.
///
/// `.none` is for open-ended goals with no schedule at all, e.g. "eat healthier" —
/// these don't get tick-box tracking or calendar entries, just a place to sit
/// and be revisited.
enum RecurrenceFrequency: String, Codable, CaseIterable {
    case none
    case daily
    case weekly
    case custom
}

/// A goal that generates its own recurring calendar entries and
/// tracks whether you completed it on each given day.
struct Goal: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String                      // e.g. "Read for 30 minutes"
    var frequency: RecurrenceFrequency = .none
    var durationMinutes: Int? = nil        // optional — not every goal is time-based
    var categoryID: UUID? = nil            // optional — a goal doesn't have to belong to a category
    var createdDate: Date = Date()

    // A dictionary mapping each day to whether you completed the goal.
    // true = done that day, false = missed it, and a day simply not being
    // a key yet means it hasn't happened. This drives both the streak dots
    // and the progress percentage on the Goals page.
    var completions: [Date: Bool] = [:]
}

// MARK: - Settings

/// The user's app-wide preferences: their categories, and which hours
/// show on the Daily calendar. This is the one piece of data that isn't
/// tied to a specific event or goal — it's app configuration, so it'll
/// get saved and loaded separately from everything else.
struct AppSettings: Codable {
    var categories: [CalendarCategory] = CalendarCategory.defaultCategories

    // Stored as 24-hour integers (6 = 6 AM, 24 = midnight) to match the
    // "From / To" time pickers on the Settings page.
    var dailyCalendarStartHour: Int = 6
    var dailyCalendarEndHour: Int = 24
}
