import Foundation

// MARK: - Category

/// Which "life area" calendar an event or goal belongs to.
///
/// This used to be a fixed `enum`, but since you want to create, rename,
/// and recolor categories yourself from Settings, it needs to be a `struct`
/// instead — real data you make, not a fixed list baked into the code.
struct CalendarCategory: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String

    // Stored as a hex string like "#4A7FE8" — simple to save to disk and
    // easy to turn into a SwiftUI `Color` when it's time to draw something.
    var colorHex: String

    /// What a brand-new user starts with. You said Work / Personal / School
    /// as sensible defaults — these get created once, the first time the
    /// app runs, and from then on the user's own edits take over.
    static let defaultCategories: [CalendarCategory] = [
        CalendarCategory(name: "Work", colorHex: "#4A7FE8"),
        CalendarCategory(name: "Personal", colorHex: "#8E5CC7"),
        CalendarCategory(name: "School", colorHex: "#C9922E")
    ]
}

// MARK: - Event

/// A single event living inside one of the category calendars.
///
/// This is a `struct`, not a `class`. In Swift, structs are the default
/// choice for plain data — they're copied by value (similar to how a
/// JS object gets cloned with spread syntax `{...obj}`), which avoids bugs
/// where two different parts of your app accidentally share and mutate
/// the same object without meaning to.
struct CalendarEvent: Identifiable, Codable {
    var id: UUID = UUID()              // a unique ID, generated automatically
    var title: String
    var notes: String = ""
    var startDate: Date
    var endDate: Date

    // Points at a CalendarCategory's `id` rather than storing the category
    // itself. This way, if you rename "Work" to "Job" in Settings, every
    // event tagged with it updates automatically — there's only ever one
    // copy of the category's actual name and color.
    var categoryID: UUID

    // Whether this event appears on the Daily calendar's 30-minute grid.
    // If false, it only lives on the Long-Term calendar.
    var flowsToDaily: Bool = false

    // `UUID?` means "a UUID, or nothing at all" — this is an Optional.
    // Swift forces you to handle the "nothing" case explicitly, which is
    // stricter than JS/Python but catches a lot of bugs before they happen.
    var linkedGoalID: UUID? = nil      // set only if this event was generated by a Goal
    var isCompleted: Bool = false      // relevant for goal-linked events you can "tick off"
}

// MARK: - Goal

/// A single checkpoint inside a long-term goal, e.g. "Submit thesis
/// proposal" as one step toward "Finish degree". Optionally scheduled
/// onto the calendar with a real date.
struct Milestone: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String
    var done: Bool = false
    var addToCalendar: Bool = false
    var date: Date? = nil   // only meaningful when addToCalendar is true
}

/// A dated check-in on an open-ended goal, e.g. "Started meal prepping"
/// for a goal like "Eat healthier" that has no clear milestones.
struct GoalNote: Identifiable, Codable {
    var id: UUID = UUID()
    var date: Date = Date()
    var text: String
}

/// Whether a goal lives in the Short-term or Long-term section of the
/// Goals page. Kept as its own explicit flag rather than inferred from
/// `frequency`, since "why is this goal showing up here" should always
/// be obvious just by reading the code.
enum GoalKind: String, Codable {
    case shortTerm
    case longTerm
}

/// How often a goal repeats.
///
/// `.none` is for open-ended goals with no schedule at all, e.g. "eat healthier" —
/// these don't get tick-box tracking or calendar entries, just a place to sit
/// and be revisited.
enum RecurrenceFrequency: String, Codable, CaseIterable {
    case none
    case daily
    case weekly
    case custom
}

/// A goal that generates its own recurring calendar entries and
/// tracks whether you completed it on each given day.
struct Goal: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String                      // e.g. "Read for 30 minutes"
    var kind: GoalKind = .shortTerm
    var frequency: RecurrenceFrequency = .none
    var durationMinutes: Int? = nil        // optional — not every goal is time-based
    var categoryID: UUID? = nil            // optional — a goal doesn't have to belong to a category
    var createdDate: Date = Date()

    // A dictionary mapping each day to whether you completed the goal.
    // true = done that day, false = missed it, and a day simply not being
    // a key yet means it hasn't happened. This drives both the streak dots
    // and the progress percentage on the Goals page.
    // Completion history, keyed by day.
    //
    // Stored with String keys rather than Date keys for one specific
    // reason: JSON requires string keys, and Swift silently encodes a
    // [Date: Bool] dictionary as a flat alternating array instead —
    // which works, but produces a file that's confusing to read and
    // easy to break later. `dayKey(_:)` below converts a Date to the
    // canonical "yyyy-MM-dd" string, and the helpers in GoalHelpers
    // mean the rest of the app never has to think about it.
    var completions: [String: Bool] = [:]

    /// The canonical string key for a given day — always local-calendar
    /// based, so "today" means today where you are.
    static func dayKey(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = Calendar.current
        formatter.timeZone = TimeZone.current
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }

    // The two ways a long-term goal can track progress — milestones with
    // real dates, or a running log of notes for open-ended goals. A goal
    // only ever really uses one or the other, decided by whether
    // `milestones` is empty.
    var milestones: [Milestone] = []
    var notes: [GoalNote] = []

    // Set only on a short-term goal that's a "daily habit" belonging to
    // a specific long-term goal (e.g. "Study 1 hour" under "Finish degree").
    // `nil` means it's a standalone short-term goal.
    var linkedToGoalID: UUID? = nil

    // Which days of the week this goal is scheduled for. Numbers follow
    // Foundation's own weekday convention: 1 = Sunday ... 7 = Saturday
    // (this matches what `Calendar.component(.weekday, from:)` returns,
    // which is what the scheduling logic in GoalHelpers.swift checks
    // against). Defaults to every day.
    var repeatDays: Set<Int> = Goal.allDays

    static let allDays: Set<Int> = Set(1...7)
    static let weekdaysOnly: Set<Int> = [2, 3, 4, 5, 6]   // Monday–Friday
    static let weekendOnly: Set<Int> = [1, 7]              // Saturday–Sunday

    // Optional, on a short-term goal: the last day it's active, e.g.
    // "read 30 min/day for 2 months". `nil` means it repeats indefinitely.
    var endDate: Date? = nil

    // Optional, on a long-term goal: an overall deadline for the whole
    // goal, e.g. "finish the degree by August 2027" — separate from any
    // individual milestone's own date.
    var targetDate: Date? = nil
}

// MARK: - Settings

/// The user's app-wide preferences: their categories, and which hours
/// show on the Daily calendar. This is the one piece of data that isn't
/// tied to a specific event or goal — it's app configuration, so it'll
/// get saved and loaded separately from everything else.
struct AppSettings: Codable {
    var categories: [CalendarCategory] = CalendarCategory.defaultCategories

    // Stored as 24-hour integers (6 = 6 AM, 24 = midnight) to match the
    // "From / To" time pickers on the Settings page.
    var dailyCalendarStartHour: Int = 6
    var dailyCalendarEndHour: Int = 24
}

