import Foundation

// MARK: - Category

/// Which "life area" calendar an event or goal belongs to.
///
/// This used to be a fixed `enum`, but since you want to create, rename,
/// and recolor categories yourself from Settings, it needs to be a `struct`
/// instead — real data you make, not a fixed list baked into the code.
struct CalendarCategory: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var name: String

    // Stored as a hex string like "#4A7FE8" — simple to save to disk and
    // easy to turn into a SwiftUI `Color` when it's time to draw something.
    var colorHex: String

    /// What a brand-new user starts with. You said Work / Personal / School
    /// as sensible defaults — these get created once, the first time the
    /// app runs, and from then on the user's own edits take over.
    ///
    /// The IDs are FIXED rather than randomly generated. That matters:
    /// events store a categoryID pointing at one of these, and if the
    /// defaults got fresh random IDs on some later launch, every event
    /// would suddenly point at a category that no longer exists and
    /// lose its colour.
    static let defaultCategories: [CalendarCategory] = [
        CalendarCategory(id: UUID(uuidString: "00000000-0000-0000-0000-00000000C001")!, name: "Work", colorHex: "#4A7FE8"),
        CalendarCategory(id: UUID(uuidString: "00000000-0000-0000-0000-00000000C002")!, name: "Personal", colorHex: "#8E5CC7"),
        CalendarCategory(id: UUID(uuidString: "00000000-0000-0000-0000-00000000C003")!, name: "School", colorHex: "#C9922E")
    ]
}

// MARK: - Event

/// How often an event repeats.
enum EventRecurrence: String, Codable, CaseIterable, Identifiable {
    case none, daily, weekly, monthly

    var id: String { rawValue }

    var label: String {
        switch self {
        case .none: return "Never"
        case .daily: return "Every day"
        case .weekly: return "Every week"
        case .monthly: return "Every month"
        }
    }
}

/// Where an event was created — Daily's tap-to-add, or Long-Term's
/// add-event button.
///
/// This exists specifically to keep two separate questions from
/// tangling together: "should this also show on the Daily grid"
/// (`flowsToDaily`) and "should this show on Long-Term" (this). A timed
/// event added from Long-Term should still show on Long-Term even
/// though it also gets `flowsToDaily = true` for the Daily grid — those
/// are independent facts, and conflating them was the actual bug.
enum EventOrigin: String, Codable {
    case daily
    case longTerm
}

/// A single event living inside one of the category calendars.
///
/// This is a `struct`, not a `class`. In Swift, structs are the default
/// choice for plain data — they're copied by value (similar to how a
/// JS object gets cloned with spread syntax `{...obj}`), which avoids bugs
/// where two different parts of your app accidentally share and mutate
/// the same object without meaning to.
struct CalendarEvent: Identifiable, Codable {
    var id: UUID = UUID()              // a unique ID, generated automatically
    var title: String
    var notes: String = ""
    var startDate: Date
    var endDate: Date

    // Points at a CalendarCategory's `id` rather than storing the category
    // itself. This way, if you rename "Work" to "Job" in Settings, every
    // event tagged with it updates automatically — there's only ever one
    // copy of the category's actual name and color.
    var categoryID: UUID

    // Whether this event appears on the Daily calendar's 30-minute grid.
    // If false, it only lives on the Long-Term calendar.
    var flowsToDaily: Bool = false

    /// An event with no specific time — a holiday, a birthday, a
    /// deadline. All-day events never appear on the Daily grid, since
    /// there's no time slot to put them in.
    var isAllDay: Bool = false

    /// How often this repeats. Occurrences are calculated on the fly
    /// rather than stored, same approach as recurring finance events —
    /// so a weekly event is one row in the data, not fifty.
    var recurrence: EventRecurrence = .none

    /// When a repeating event stops. `nil` means it repeats indefinitely.
    var recurrenceEndDate: Date? = nil

    // `UUID?` means "a UUID, or nothing at all" — this is an Optional.
    // Swift forces you to handle the "nothing" case explicitly, which is
    // stricter than JS/Python but catches a lot of bugs before they happen.
    var linkedGoalID: UUID? = nil      // set only if this event was generated by a Goal
    var isCompleted: Bool = false      // relevant for goal-linked events you can "tick off"

    /// Optionally ties this event to someone from the People page —
    /// "Call Sheryl" being the obvious case. Opening the event then
    /// gives you their contact actions directly.
    var linkedPersonID: UUID? = nil

    /// Days to skip for a repeating event — what "delete just this
    /// occurrence" writes to, rather than removing the event outright
    /// and losing every future occurrence too. Only meaningful when
    /// `recurrence != .none`.
    var excludedOccurrences: Set<String> = []

    /// Which screen this event was created from.
    ///
    /// Kept separate from `flowsToDaily` on purpose. That flag answers
    /// "does this also get a slot on the Daily grid"; this answers
    /// "should this show on Long-Term". Using one flag for both meant a
    /// timed event added from Long-Term vanished from the screen it was
    /// created on, because giving it a time set flowsToDaily, which the
    /// Long-Term filter then read as "hide this".
    var origin: EventOrigin = .daily

    /// Which weekdays a `.daily` repeat actually lands on, using the
    /// same 1=Sunday convention as `Goal.repeatDays`.
    ///
    /// Defaults to all seven, so "every day" means every day unless you
    /// narrow it — which is what lets a work block repeat Monday to
    /// Friday without appearing at the weekend. Ignored for the other
    /// recurrence types.
    var repeatDays: Set<Int> = Set(1...7)

    // MARK: - Codable
    //
    // Hand-written for the same reason as Goal's — this struct has
    // grown several times this session (isAllDay, recurrence,
    // linkedPersonID...), and Swift's automatic decoder doesn't fall
    // back to a default value for a key missing from old saved JSON;
    // it just fails the whole object. Writing this by hand with
    // `decodeIfPresent(...) ?? default` means old saved events keep
    // decoding correctly no matter how many fields get added later.
    enum CodingKeys: String, CodingKey {
        case id, title, notes, startDate, endDate, categoryID, flowsToDaily
        case isAllDay, recurrence, recurrenceEndDate
        case linkedGoalID, isCompleted, linkedPersonID, excludedOccurrences, origin, repeatDays
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        title = try c.decode(String.self, forKey: .title)
        notes = try c.decodeIfPresent(String.self, forKey: .notes) ?? ""
        startDate = try c.decode(Date.self, forKey: .startDate)
        endDate = try c.decode(Date.self, forKey: .endDate)
        categoryID = try c.decode(UUID.self, forKey: .categoryID)
        flowsToDaily = try c.decodeIfPresent(Bool.self, forKey: .flowsToDaily) ?? false
        isAllDay = try c.decodeIfPresent(Bool.self, forKey: .isAllDay) ?? false
        recurrence = try c.decodeIfPresent(EventRecurrence.self, forKey: .recurrence) ?? .none
        recurrenceEndDate = try c.decodeIfPresent(Date.self, forKey: .recurrenceEndDate)
        linkedGoalID = try c.decodeIfPresent(UUID.self, forKey: .linkedGoalID)
        isCompleted = try c.decodeIfPresent(Bool.self, forKey: .isCompleted) ?? false
        linkedPersonID = try c.decodeIfPresent(UUID.self, forKey: .linkedPersonID)
        excludedOccurrences = try c.decodeIfPresent(Set<String>.self, forKey: .excludedOccurrences) ?? []
        origin = try c.decodeIfPresent(EventOrigin.self, forKey: .origin) ?? .daily
        repeatDays = try c.decodeIfPresent(Set<Int>.self, forKey: .repeatDays) ?? Set(1...7)
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(title, forKey: .title)
        try c.encode(notes, forKey: .notes)
        try c.encode(startDate, forKey: .startDate)
        try c.encode(endDate, forKey: .endDate)
        try c.encode(categoryID, forKey: .categoryID)
        try c.encode(flowsToDaily, forKey: .flowsToDaily)
        try c.encode(isAllDay, forKey: .isAllDay)
        try c.encode(recurrence, forKey: .recurrence)
        try c.encodeIfPresent(recurrenceEndDate, forKey: .recurrenceEndDate)
        try c.encodeIfPresent(linkedGoalID, forKey: .linkedGoalID)
        try c.encode(isCompleted, forKey: .isCompleted)
        try c.encodeIfPresent(linkedPersonID, forKey: .linkedPersonID)
        try c.encode(excludedOccurrences, forKey: .excludedOccurrences)
        try c.encode(origin, forKey: .origin)
        try c.encode(repeatDays, forKey: .repeatDays)
    }

    /// The plain memberwise initializer, restated because writing a
    /// custom `init(from:)` above switches off Swift's automatic one.
    init(
        id: UUID = UUID(),
        title: String,
        notes: String = "",
        startDate: Date,
        endDate: Date,
        categoryID: UUID,
        flowsToDaily: Bool = false,
        isAllDay: Bool = false,
        recurrence: EventRecurrence = .none,
        recurrenceEndDate: Date? = nil,
        linkedGoalID: UUID? = nil,
        isCompleted: Bool = false,
        linkedPersonID: UUID? = nil,
        excludedOccurrences: Set<String> = [],
        origin: EventOrigin = .daily,
        repeatDays: Set<Int> = Set(1...7)
    ) {
        self.id = id
        self.title = title
        self.notes = notes
        self.startDate = startDate
        self.endDate = endDate
        self.categoryID = categoryID
        self.flowsToDaily = flowsToDaily
        self.isAllDay = isAllDay
        self.recurrence = recurrence
        self.recurrenceEndDate = recurrenceEndDate
        self.linkedGoalID = linkedGoalID
        self.isCompleted = isCompleted
        self.linkedPersonID = linkedPersonID
        self.excludedOccurrences = excludedOccurrences
        self.origin = origin
        self.repeatDays = repeatDays
    }
}

extension CalendarEvent {
    /// How many days this event spans. 1 for a normal same-day event.
    var dayCount: Int {
        let calendar = Calendar.current
        let start = calendar.startOfDay(for: startDate)
        let end = calendar.startOfDay(for: endDate)
        return (calendar.dateComponents([.day], from: start, to: end).day ?? 0) + 1
    }

    var isMultiDay: Bool { dayCount > 1 }

    /// Whether this event covers a given day — accounting for multi-day
    /// spans and repeats, not just a matching start date.
    func occupies(_ date: Date) -> Bool {
        let calendar = Calendar.current
        let day = calendar.startOfDay(for: date)

        // Checked first, before anything else: an occurrence someone
        // deliberately deleted stays gone regardless of which other
        // rule would otherwise place the event on this day.
        if excludedOccurrences.contains(Goal.dayKey(day)) { return false }

        let start = calendar.startOfDay(for: startDate)
        let end = calendar.startOfDay(for: endDate)

        // The original span, or any day inside it for multi-day events.
        if day >= start && day <= end { return true }
        guard recurrence != .none, day > end else { return false }

        // Past the end of a repeating event's run.
        if let limit = recurrenceEndDate, day > calendar.startOfDay(for: limit) { return false }

        switch recurrence {
        case .none:
            return false
        case .daily:
            // Narrowed by repeatDays, so "every day" can mean weekdays
            // only without needing a separate recurrence type.
            return repeatDays.contains(calendar.component(.weekday, from: day))
        case .weekly:
            return calendar.component(.weekday, from: day) == calendar.component(.weekday, from: start)
        case .monthly:
            let targetDay = calendar.component(.day, from: start)
            let daysThisMonth = calendar.range(of: .day, in: .month, for: day)?.count ?? 28
            // Clamp so a 31st anchor still lands in shorter months.
            return calendar.component(.day, from: day) == min(targetDay, daysThisMonth)
        }
    }

    /// This event's start and end on a specific day. For a repeat, the
    /// original times shifted onto that day; otherwise just its own.
    func times(on date: Date) -> (start: Date, end: Date) {
        let calendar = Calendar.current
        guard recurrence != .none,
              !calendar.isDate(startDate, inSameDayAs: date) else {
            return (startDate, endDate)
        }
        let duration = endDate.timeIntervalSince(startDate)
        let comps = calendar.dateComponents([.hour, .minute], from: startDate)
        let shifted = calendar.date(
            bySettingHour: comps.hour ?? 0,
            minute: comps.minute ?? 0,
            second: 0,
            of: date
        ) ?? date
        return (shifted, shifted.addingTimeInterval(duration))
    }
}

// MARK: - Goal

/// A single checkpoint inside a long-term goal, e.g. "Submit thesis
/// proposal" as one step toward "Finish degree". Optionally scheduled
/// onto the calendar with a real date.
struct Milestone: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String
    var done: Bool = false
    var addToCalendar: Bool = false
    var date: Date? = nil   // only meaningful when addToCalendar is true
}

/// A dated check-in on an open-ended goal, e.g. "Started meal prepping"
/// for a goal like "Eat healthier" that has no clear milestones.
struct GoalNote: Identifiable, Codable {
    var id: UUID = UUID()
    var date: Date = Date()
    var text: String
}

/// Whether a goal lives in the Short-term or Long-term section of the
/// Goals page. Kept as its own explicit flag rather than inferred from
/// `frequency`, since "why is this goal showing up here" should always
/// be obvious just by reading the code.
enum GoalKind: String, Codable {
    case shortTerm
    case longTerm
}

/// How often a goal repeats.
///
/// `.none` is for open-ended goals with no schedule at all, e.g. "eat healthier" —
/// these don't get tick-box tracking or calendar entries, just a place to sit
/// and be revisited.
enum RecurrenceFrequency: String, Codable, CaseIterable {
    case none
    case daily
    case weekly
    case custom
}

/// A goal that generates its own recurring calendar entries and
/// tracks whether you completed it on each given day.
/// How a short-term goal's schedule works.
///
/// `.specificDays` is the original model — repeats on chosen weekdays,
/// one completion per day. The other two cover things that model can't:
/// "workout 3 times a week" doesn't care *which* days, just a weekly
/// total, and "drink water 4 times a day" needs more than one
/// completion per day, which a simple true/false can't represent.
enum GoalFrequencyType: String, Codable {
    case specificDays
    case timesPerWeek
    case timesPerDay
}

struct Goal: Identifiable, Codable {
    var id: UUID = UUID()
    var title: String                      // e.g. "Read for 30 minutes"
    var kind: GoalKind = .shortTerm
    var frequency: RecurrenceFrequency = .none
    var durationMinutes: Int? = nil        // optional — not every goal is time-based
    var categoryID: UUID? = nil            // optional — a goal doesn't have to belong to a category
    var createdDate: Date = Date()

    // A dictionary mapping each day to whether you completed the goal.
    // true = done that day, false = missed it, and a day simply not being
    // a key yet means it hasn't happened. This drives both the streak dots
    // and the progress percentage on the Goals page.
    // Completion history, keyed by day.
    //
    // Stored with String keys rather than Date keys for one specific
    // reason: JSON requires string keys, and Swift silently encodes a
    // [Date: Bool] dictionary as a flat alternating array instead —
    // which works, but produces a file that's confusing to read and
    // easy to break later. `dayKey(_:)` below converts a Date to the
    // canonical "yyyy-MM-dd" string, and the helpers in GoalHelpers
    // mean the rest of the app never has to think about it.
    var completions: [String: Bool] = [:]

    /// The canonical string key for a given day — always local-calendar
    /// based, so "today" means today where you are.
    static func dayKey(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = Calendar.current
        formatter.timeZone = TimeZone.current
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }

    // The two ways a long-term goal can track progress — milestones with
    // real dates, or a running log of notes for open-ended goals. A goal
    // only ever really uses one or the other, decided by whether
    // `milestones` is empty.
    var milestones: [Milestone] = []
    var notes: [GoalNote] = []

    // Set only on a short-term goal that's a "daily habit" belonging to
    // a specific long-term goal (e.g. "Study 1 hour" under "Finish degree").
    // `nil` means it's a standalone short-term goal.
    var linkedToGoalID: UUID? = nil

    // Which days of the week this goal is scheduled for. Numbers follow
    // Foundation's own weekday convention: 1 = Sunday ... 7 = Saturday
    // (this matches what `Calendar.component(.weekday, from:)` returns,
    // which is what the scheduling logic in GoalHelpers.swift checks
    // against). Defaults to every day.
    var repeatDays: Set<Int> = Goal.allDays

    static let allDays: Set<Int> = Set(1...7)
    static let weekdaysOnly: Set<Int> = [2, 3, 4, 5, 6]   // Monday–Friday
    static let weekendOnly: Set<Int> = [1, 7]              // Saturday–Sunday

    // MARK: - Calendar scheduling
    //
    // A goal can put itself on the daily planner at a set time — "read
    // for 30 minutes" showing up every evening at 9pm.
    //
    // These blocks are NOT stored as calendar events. They're generated
    // on the fly from the goal's own schedule (`repeatDays`, `endDate`)
    // whenever a day is drawn. That means there's one goal rather than
    // hundreds of duplicated event rows, and editing the goal updates
    // every day at once instead of needing everything regenerated.

    var scheduledOnCalendar: Bool = false

    /// Start time as minutes from midnight — 1260 is 9:00pm. Stored as
    /// a plain number rather than a Date because the time repeats across
    /// many days; pinning it to one date would be misleading.
    var scheduledStartMinutes: Int = 21 * 60

    var scheduledDurationMinutes: Int = 30

    // Optional, on a short-term goal: the last day it's active, e.g.
    // "read 30 min/day for 2 months". `nil` means it repeats indefinitely.
    var endDate: Date? = nil

    // Optional, on a long-term goal: an overall deadline for the whole
    // goal, e.g. "finish the degree by August 2027" — separate from any
    // individual milestone's own date.
    var targetDate: Date? = nil

    // MARK: - Challenge tracking
    //
    // Set only on a long-term goal created by starting a challenge like
    // 75 Hard. A challenge is deliberately just a normal goal with a
    // head start — these fields add the extra bits challenges need
    // (a start date to count days from, strict mode) without making
    // challenges a separate type the whole app has to know about.

    var challengeTemplateID: String? = nil
    var challengeStartDate: Date? = nil

    /// When true, missing any task on any day resets the challenge to
    /// day one — the original 75 Hard rule. Off by default, and only
    /// offered for challenges whose rules actually work that way.
    var challengeStrictMode: Bool = false

    /// How many times this challenge has been restarted after a miss.
    /// Kept so past attempts stay visible rather than vanishing.
    var challengeAttempt: Int = 1

    // MARK: - Linked app
    //
    // A goal can point at an app to open directly — "Read for 30 min"
    // opening Books, say. Both the scheme and the display name are
    // stored so the goal still shows something sensible even if the
    // app is later uninstalled or the catalog changes.

    var linkedAppScheme: String? = nil
    var linkedAppName: String? = nil
    var linkedAppID: String? = nil

    /// Optionally ties this goal to someone from the People page —
    /// "call a friend weekly", say. Low-traffic, so it sits at the
    /// bottom of the goal editor rather than competing for attention.
    var linkedPersonID: UUID? = nil

    // MARK: - Frequency

    var frequencyType: GoalFrequencyType = .specificDays
    var timesPerWeekTarget: Int = 3
    var timesPerDayTarget: Int = 2

    /// How many times you've done a `.timesPerDay` goal on a given day.
    /// Separate from `completions` (which stays a simple true/false)
    /// since a count needs a number, not a bool. `.specificDays` and
    /// `.timesPerWeek` goals never touch this.
    var completionCounts: [String: Int] = [:]

    /// Per-day exceptions to `scheduledStartMinutes` — what dragging a
    /// single occurrence on the Daily planner writes to, rather than
    /// moving every day. A day with no entry here just uses the goal's
    /// normal scheduled time; changing that time in the goal editor
    /// updates every day EXCEPT ones with their own override here,
    /// exactly mirroring how "delete just this occurrence" works for
    /// repeating calendar events.
    var scheduledTimeOverrides: [String: Int] = [:]

    // MARK: - Codable
    //
    // Written by hand rather than left to Swift's automatic synthesis.
    // This matters because this struct keeps growing — nearly every
    // session so far has added new fields — and Swift's auto-generated
    // decoder does NOT fall back to a property's default value when a
    // key is missing from old saved JSON; it just fails to decode the
    // whole object. `PersistenceManager` catches that failure quietly,
    // so the practical effect was: every time a field got added, your
    // previously saved goals would silently vanish on the next run.
    //
    // `decodeIfPresent(...) ?? default` for every field means old files
    // always decode successfully, picking up sensible defaults for
    // whatever's missing, however many fields get added from here on.
    enum CodingKeys: String, CodingKey {
        case id, title, kind, frequency, durationMinutes, categoryID, createdDate
        case completions, milestones, notes, linkedToGoalID, repeatDays
        case scheduledOnCalendar, scheduledStartMinutes, scheduledDurationMinutes
        case endDate, targetDate
        case challengeTemplateID, challengeStartDate, challengeStrictMode, challengeAttempt
        case linkedAppScheme, linkedAppName, linkedAppID, linkedPersonID
        case frequencyType, timesPerWeekTarget, timesPerDayTarget, completionCounts, scheduledTimeOverrides
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        title = try c.decodeIfPresent(String.self, forKey: .title) ?? ""
        kind = try c.decodeIfPresent(GoalKind.self, forKey: .kind) ?? .shortTerm
        frequency = try c.decodeIfPresent(RecurrenceFrequency.self, forKey: .frequency) ?? .none
        durationMinutes = try c.decodeIfPresent(Int.self, forKey: .durationMinutes)
        categoryID = try c.decodeIfPresent(UUID.self, forKey: .categoryID)
        createdDate = try c.decodeIfPresent(Date.self, forKey: .createdDate) ?? Date()
        completions = try c.decodeIfPresent([String: Bool].self, forKey: .completions) ?? [:]
        milestones = try c.decodeIfPresent([Milestone].self, forKey: .milestones) ?? []
        notes = try c.decodeIfPresent([GoalNote].self, forKey: .notes) ?? []
        linkedToGoalID = try c.decodeIfPresent(UUID.self, forKey: .linkedToGoalID)
        repeatDays = try c.decodeIfPresent(Set<Int>.self, forKey: .repeatDays) ?? Goal.allDays
        scheduledOnCalendar = try c.decodeIfPresent(Bool.self, forKey: .scheduledOnCalendar) ?? false
        scheduledStartMinutes = try c.decodeIfPresent(Int.self, forKey: .scheduledStartMinutes) ?? 21 * 60
        scheduledDurationMinutes = try c.decodeIfPresent(Int.self, forKey: .scheduledDurationMinutes) ?? 30
        endDate = try c.decodeIfPresent(Date.self, forKey: .endDate)
        targetDate = try c.decodeIfPresent(Date.self, forKey: .targetDate)
        challengeTemplateID = try c.decodeIfPresent(String.self, forKey: .challengeTemplateID)
        challengeStartDate = try c.decodeIfPresent(Date.self, forKey: .challengeStartDate)
        challengeStrictMode = try c.decodeIfPresent(Bool.self, forKey: .challengeStrictMode) ?? false
        challengeAttempt = try c.decodeIfPresent(Int.self, forKey: .challengeAttempt) ?? 1
        linkedAppScheme = try c.decodeIfPresent(String.self, forKey: .linkedAppScheme)
        linkedAppName = try c.decodeIfPresent(String.self, forKey: .linkedAppName)
        linkedAppID = try c.decodeIfPresent(String.self, forKey: .linkedAppID)
        linkedPersonID = try c.decodeIfPresent(UUID.self, forKey: .linkedPersonID)
        frequencyType = try c.decodeIfPresent(GoalFrequencyType.self, forKey: .frequencyType) ?? .specificDays
        timesPerWeekTarget = try c.decodeIfPresent(Int.self, forKey: .timesPerWeekTarget) ?? 3
        timesPerDayTarget = try c.decodeIfPresent(Int.self, forKey: .timesPerDayTarget) ?? 2
        completionCounts = try c.decodeIfPresent([String: Int].self, forKey: .completionCounts) ?? [:]
        scheduledTimeOverrides = try c.decodeIfPresent([String: Int].self, forKey: .scheduledTimeOverrides) ?? [:]
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(title, forKey: .title)
        try c.encode(kind, forKey: .kind)
        try c.encode(frequency, forKey: .frequency)
        try c.encodeIfPresent(durationMinutes, forKey: .durationMinutes)
        try c.encodeIfPresent(categoryID, forKey: .categoryID)
        try c.encode(createdDate, forKey: .createdDate)
        try c.encode(completions, forKey: .completions)
        try c.encode(milestones, forKey: .milestones)
        try c.encode(notes, forKey: .notes)
        try c.encodeIfPresent(linkedToGoalID, forKey: .linkedToGoalID)
        try c.encode(repeatDays, forKey: .repeatDays)
        try c.encode(scheduledOnCalendar, forKey: .scheduledOnCalendar)
        try c.encode(scheduledStartMinutes, forKey: .scheduledStartMinutes)
        try c.encode(scheduledDurationMinutes, forKey: .scheduledDurationMinutes)
        try c.encodeIfPresent(endDate, forKey: .endDate)
        try c.encodeIfPresent(targetDate, forKey: .targetDate)
        try c.encodeIfPresent(challengeTemplateID, forKey: .challengeTemplateID)
        try c.encodeIfPresent(challengeStartDate, forKey: .challengeStartDate)
        try c.encode(challengeStrictMode, forKey: .challengeStrictMode)
        try c.encode(challengeAttempt, forKey: .challengeAttempt)
        try c.encodeIfPresent(linkedAppScheme, forKey: .linkedAppScheme)
        try c.encodeIfPresent(linkedAppName, forKey: .linkedAppName)
        try c.encodeIfPresent(linkedAppID, forKey: .linkedAppID)
        try c.encodeIfPresent(linkedPersonID, forKey: .linkedPersonID)
        try c.encode(frequencyType, forKey: .frequencyType)
        try c.encode(timesPerWeekTarget, forKey: .timesPerWeekTarget)
        try c.encode(timesPerDayTarget, forKey: .timesPerDayTarget)
        try c.encode(completionCounts, forKey: .completionCounts)
        try c.encode(scheduledTimeOverrides, forKey: .scheduledTimeOverrides)
    }

    /// The plain memberwise initializer Swift would otherwise generate
    /// automatically — writing a custom `init(from:)` above switches
    /// that off, so it needs restating explicitly for all the places
    /// in the app that construct a Goal directly (`Goal(title: "...")`,
    /// and so on) rather than decoding one from JSON.
    init(
        id: UUID = UUID(),
        title: String,
        kind: GoalKind = .shortTerm,
        frequency: RecurrenceFrequency = .none,
        durationMinutes: Int? = nil,
        categoryID: UUID? = nil,
        createdDate: Date = Date(),
        completions: [String: Bool] = [:],
        milestones: [Milestone] = [],
        notes: [GoalNote] = [],
        linkedToGoalID: UUID? = nil,
        repeatDays: Set<Int> = Goal.allDays,
        scheduledOnCalendar: Bool = false,
        scheduledStartMinutes: Int = 21 * 60,
        scheduledDurationMinutes: Int = 30,
        endDate: Date? = nil,
        targetDate: Date? = nil,
        challengeTemplateID: String? = nil,
        challengeStartDate: Date? = nil,
        challengeStrictMode: Bool = false,
        challengeAttempt: Int = 1,
        linkedAppScheme: String? = nil,
        linkedAppName: String? = nil,
        linkedAppID: String? = nil,
        linkedPersonID: UUID? = nil,
        frequencyType: GoalFrequencyType = .specificDays,
        timesPerWeekTarget: Int = 3,
        timesPerDayTarget: Int = 2,
        completionCounts: [String: Int] = [:],
        scheduledTimeOverrides: [String: Int] = [:]
    ) {
        self.id = id
        self.title = title
        self.kind = kind
        self.frequency = frequency
        self.durationMinutes = durationMinutes
        self.categoryID = categoryID
        self.createdDate = createdDate
        self.completions = completions
        self.milestones = milestones
        self.notes = notes
        self.linkedToGoalID = linkedToGoalID
        self.repeatDays = repeatDays
        self.scheduledOnCalendar = scheduledOnCalendar
        self.scheduledStartMinutes = scheduledStartMinutes
        self.scheduledDurationMinutes = scheduledDurationMinutes
        self.endDate = endDate
        self.targetDate = targetDate
        self.challengeTemplateID = challengeTemplateID
        self.challengeStartDate = challengeStartDate
        self.challengeStrictMode = challengeStrictMode
        self.challengeAttempt = challengeAttempt
        self.linkedAppScheme = linkedAppScheme
        self.linkedAppName = linkedAppName
        self.linkedAppID = linkedAppID
        self.linkedPersonID = linkedPersonID
        self.frequencyType = frequencyType
        self.timesPerWeekTarget = timesPerWeekTarget
        self.timesPerDayTarget = timesPerDayTarget
        self.completionCounts = completionCounts
        self.scheduledTimeOverrides = scheduledTimeOverrides
    }
}

// MARK: - Settings

/// The user's app-wide preferences: their categories, and which hours
/// show on the Daily calendar. This is the one piece of data that isn't
/// tied to a specific event or goal — it's app configuration, so it'll
/// get saved and loaded separately from everything else.
struct AppSettings: Codable {
    var categories: [CalendarCategory] = CalendarCategory.defaultCategories

    // Stored as 24-hour integers (6 = 6 AM, 24 = midnight) to match the
    // "From / To" time pickers on the Settings page.
    var dailyCalendarStartHour: Int = 6
    var dailyCalendarEndHour: Int = 24
}

