import SwiftUI
import Combine

/// The app's landing screen: what's happening right now, what's next,
/// today's goals, and a task list — each in its own bordered box,
/// matching the Goals page.
///
/// The layout is deliberately fixed. Nothing scrolls except inside the
/// goals and tasks boxes, because opening the app should answer "what
/// am I meant to be doing" at a glance, and that stops being true the
/// moment you have to scroll to find out.
struct HomeView: View {
    @ObservedObject var calendarStore: CalendarStore
    @ObservedObject var goalsStore: GoalsStore
    @ObservedObject var tasksStore: TasksStore
    @ObservedObject var appearanceStore: AppearanceStore
    @ObservedObject var journalStore: JournalStore
    @ObservedObject var planReviewStore: PlanReviewStore

    @State private var showingEveningReview = false

    @State private var newTaskText = ""

    // Ticks every 30s so "42 min left" and the current block stay
    // roughly accurate without re-rendering constantly.
    @State private var now = Date()
    private let timer = Timer.publish(every: 30, on: .main, in: .common).autoconnect()

    var body: some View {
        VStack(spacing: 14) {
            rightNowBox
            goalsBox
            tasksBox
            if showsReviewCard {
                reviewBox
            }
        }
        .padding(.horizontal)
        .padding(.bottom, 10)
        .onReceive(timer) { now = $0 }
        .sheet(isPresented: $showingEveningReview) {
            EveningReviewView(
                goalsStore: goalsStore,
                journalStore: journalStore,
                planReviewStore: planReviewStore,
                appearanceStore: appearanceStore
            )
        }
    }

    /// Quiet until it's actually relevant, and gone once done — same
    /// principle as everything else in Plan and Review. No card at all
    /// if the mode is off, before the configured time, or after
    /// today's review is already answered.
    private var showsReviewCard: Bool {
        guard planReviewStore.isEnabled else { return false }
        let calendar = Calendar.current
        let comps = calendar.dateComponents([.hour, .minute], from: now)
        let nowMinutes = (comps.hour ?? 0) * 60 + (comps.minute ?? 0)
        guard nowMinutes >= planReviewStore.eveningReviewMinutes else { return false }
        return !planReviewStore.hasReviewedToday(journalStore: journalStore)
    }

    private var reviewBox: some View {
        Button {
            showingEveningReview = true
        } label: {
            SectionBox(title: "Evening review", accent: appearanceStore.primaryColor) {
                HStack {
                    Text("A quick look back, and a line or two if you want.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Image(systemName: "chevron.right")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
        }
        .buttonStyle(.plain)
    }

    // MARK: - Event lookups

    /// Timed events on today, with repeats shifted onto today's date —
    /// including blocks generated by goals scheduled to the calendar,
    /// so "read for 30 min" at 9pm shows up as what's happening now.
    private var todaysTimedEvents: [CalendarEvent] {
        DayBlocks.blocks(on: now, calendarStore: calendarStore, goalsStore: goalsStore, tasksStore: tasksStore)
    }

    private var currentEvent: CalendarEvent? {
        todaysTimedEvents.first { $0.startDate <= now && $0.endDate > now }
    }

    private var nextEvent: CalendarEvent? {
        todaysTimedEvents
            .filter { $0.startDate > now }
            .sorted { $0.startDate < $1.startDate }
            .first
    }

    /// All-day things today — holidays, deadlines. Shown as a small
    /// line rather than competing for the "right now" slot, since
    /// they're context rather than something you're doing at 2pm.
    private var allDayEvents: [CalendarEvent] {
        calendarStore.events(on: now).filter { $0.isAllDay }
    }

    /// The accent for the Right now box — the current event's own
    /// category colour when there is one, so the box itself tells you
    /// what kind of thing you're in the middle of.
    private var nowAccent: Color {
        guard let event = currentEvent else { return appearanceStore.secondaryColor }
        if event.linkedGoalID != nil { return appearanceStore.primaryColor }
        if event.linkedTaskID != nil { return appearanceStore.tertiaryColor }
        return Color(hex: calendarStore.category(for: event.categoryID)?.colorHex ?? "#999999")
    }

    // MARK: - Right now

    private var rightNowBox: some View {
        SectionBox(
            title: "Right now",
            accent: nowAccent,
            subtitle: now.formatted(.dateTime.weekday(.abbreviated).hour().minute()),
            contentSpacing: 8
        ) {
            if let event = currentEvent {
                let minutesLeft = max(Int(event.endDate.timeIntervalSince(now) / 60), 0)
                VStack(alignment: .leading, spacing: 2) {
                    Text(event.title)
                        .font(.title2.weight(.bold))
                        .lineLimit(2)
                    Text("\(event.startDate.formatted(date: .omitted, time: .shortened)) – \(event.endDate.formatted(date: .omitted, time: .shortened)) · \(minutesLeft) min left")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            } else {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Nothing scheduled")
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(.secondary)
                    Text(nextEvent != nil
                         ? "Open until \(nextEvent!.startDate.formatted(date: .omitted, time: .shortened))."
                         : "Nothing else on today.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }

            if let next = nextEvent, currentEvent != nil {
                Divider()
                HStack(spacing: 7) {
                    Image(systemName: "arrow.right")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                    Text("\(next.title) at \(next.startDate.formatted(date: .omitted, time: .shortened))")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                    Spacer()
                }
            }

            if !allDayEvents.isEmpty {
                Divider()
                ForEach(allDayEvents) { event in
                    HStack(spacing: 7) {
                        Circle()
                            .fill(Color(hex: calendarStore.category(for: event.categoryID)?.colorHex ?? "#999999"))
                            .frame(width: 7, height: 7)
                        Text(event.title)
                            .font(.caption)
                            .lineLimit(1)
                        Spacer()
                        Text("All day")
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
    }

    // MARK: - Goals

    private var todaysGoals: [Goal] {
        goalsStore.goals.filter { $0.kind == .shortTerm && $0.isScheduled(on: now) }
    }

    private var goalsBox: some View {
        let goals = todaysGoals
        let dayKey = Goal.dayKey(now)
        let left = goals.filter { $0.completions[dayKey] != true }.count

        return SectionBox(
            title: "Today's goals",
            accent: appearanceStore.primaryColor,
            subtitle: goals.isEmpty ? nil : "\(left) left",
            contentSpacing: 0
        ) {
            if goals.isEmpty {
                Text("No goals scheduled today.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, alignment: .leading)
            } else {
                ScrollView {
                    VStack(spacing: 0) {
                        ForEach(goals) { goal in
                            Button {
                                goalsStore.setToday(goal.id, done: goal.completions[dayKey] != true)
                            } label: {
                                HStack(spacing: 9) {
                                    CompletionMark(
                                        isOn: goal.completions[dayKey] == true,
                                        size: 17,
                                        color: appearanceStore.primaryColor
                                    )
                                    Text(goal.title)
                                        .font(.subheadline)
                                        .strikethrough(goal.completions[dayKey] == true)
                                        .foregroundStyle(goal.completions[dayKey] == true ? .secondary : .primary)
                                    Spacer()
                                    if goal.scheduledOnCalendar {
                                        Text(goal.scheduledTimeText)
                                            .font(.caption2)
                                            .foregroundStyle(.secondary)
                                    }
                                }
                                .padding(.vertical, 7)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }
                .frame(maxHeight: 132)
            }
        }
    }

    // MARK: - Tasks

    private var tasksBox: some View {
        SectionBox(
            title: "Tasks",
            accent: appearanceStore.tertiaryColor,
            subtitle: tasksStore.tasks.isEmpty ? nil : "\(tasksStore.incompleteCount) left",
            contentSpacing: 0
        ) {
            ScrollView {
                VStack(spacing: 0) {
                    ForEach(tasksStore.sortedTasks) { task in
                        taskRow(task)
                    }

                    HStack(spacing: 9) {
                        Image(systemName: "plus")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .frame(width: 17)
                        TextField("Add a task", text: $newTaskText)
                            .font(.subheadline)
                            .onSubmit {
                                tasksStore.addTask(newTaskText)
                                newTaskText = ""
                            }
                    }
                    .padding(.vertical, 7)
                }
            }
        }
        .frame(maxHeight: .infinity)
    }

    private func durationLabel(_ minutes: Int) -> String {
        let h = minutes / 60
        let m = minutes % 60
        if h == 0 { return "\(m)m" }
        if m == 0 { return "\(h)h" }
        return "\(h)h \(m)m"
    }

    private func taskRow(_ task: VectisTask) -> some View {
        HStack(spacing: 9) {
            Button {
                tasksStore.toggle(task.id)
            } label: {
                CompletionMark(isOn: task.done, size: 17, color: appearanceStore.tertiaryColor)
            }
            .buttonStyle(.plain)

            Text(task.text)
                .font(.subheadline)
                .strikethrough(task.done)
                .foregroundStyle(task.done ? .secondary : .primary)

            Spacer()

            // A menu rather than a full editor — tasks stay
            // deliberately simple, so this is the one optional
            // property they carry, set in one tap rather than opening
            // a whole sheet for it.
            Menu {
                ForEach([15, 30, 45, 60, 90, 120], id: \.self) { minutes in
                    Button(durationLabel(minutes)) {
                        tasksStore.setDuration(task.id, minutes: minutes)
                    }
                }
                if task.durationMinutes != nil {
                    Button("No duration", role: .destructive) {
                        tasksStore.setDuration(task.id, minutes: nil)
                    }
                }
            } label: {
                if let minutes = task.durationMinutes {
                    Text(durationLabel(minutes))
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                } else {
                    Image(systemName: "clock")
                        .font(.caption2)
                        .foregroundStyle(.secondary.opacity(0.5))
                }
            }
            .accessibilityLabel(task.durationMinutes == nil ? "Set duration" : "Duration \(durationLabel(task.durationMinutes ?? 0))")

            Button {
                tasksStore.delete(task.id)
            } label: {
                Image(systemName: "xmark")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
            .accessibilityLabel("Delete \(task.text)")
            .buttonStyle(.plain)
        }
        .padding(.vertical, 7)
    }
}

